#!/usr/bin/env python3
"""
Turn the grayscale area map (SanFranGrey.png) into an e-paper-ready 1bpp dithered
bitmap sized to the full 800x480 panel, emitted as a C header the firmware blits
directly as the MAP screen background.

The panel is 1-bit black/white (GxEPD2_BW), so the gray map is Floyd-Steinberg
dithered. We deliberately LIGHTEN it first so the land reads as a faint texture
and the black overlays the firmware draws on top (range rings, YOU marker, the
plane, labels) stay legible.

Output:
  firmware/src/generated/gen_map.h    MAP_BG : 800x480 1bpp, 1=black

Run from the repo root:
    python3 tools/build_map.py
    python3 tools/build_map.py --src Map/SanFranGrey.png --lighten 0.55
"""
import argparse, os
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_H = os.path.join(ROOT, "firmware", "src", "generated", "gen_map.h")
PREVIEW = os.path.join(ROOT, "firmware", "src", "generated", "gen_map_preview.png")

W, H = 800, 480


def cover_resize(im, w, h):
    """Scale to fully cover w x h, then center-crop."""
    sw, sh = im.size
    s = max(w / sw, h / sh)
    nw, nh = round(sw * s), round(sh * s)
    im = im.resize((nw, nh), Image.LANCZOS)
    x0 = (nw - w) // 2
    y0 = (nh - h) // 2
    return im.crop((x0, y0, x0 + w, y0 + h))


def process(path, lighten, contrast, edge):
    g = Image.open(path).convert("L")
    g = cover_resize(g, W, H)
    a = np.asarray(g, dtype=np.float32)
    # The source is a very low-contrast light-gray relief map: land and water sit
    # within a narrow band, so a plain dither turns to uniform noise and the coast
    # vanishes. Stretch the used range to full 0..255 (percentile clip kills
    # outliers), then push contrast so the bay/shoreline read as distinct tones.
    lo, hi = np.percentile(a, 2), np.percentile(a, 98)
    a = np.clip((a - lo) / max(hi - lo, 1.0), 0, 1) * 255.0
    mid = 128.0
    a = np.clip((a - mid) * contrast + mid, 0, 255)
    # Detect the OUTLINE (coastline/edges) on the high-contrast tones via Sobel
    # gradient magnitude -- BEFORE lightening, so the edge signal stays strong.
    mag = np.zeros_like(a)
    if edge > 0:
        gx = np.zeros_like(a); gy = np.zeros_like(a)
        gx[:, 1:-1] = a[:, 2:] - a[:, :-2]
        gy[1:-1, :] = a[2:, :] - a[:-2, :]
        mag = np.sqrt(gx * gx + gy * gy)
        mag = np.clip(mag / max(np.percentile(mag, 99), 1.0), 0, 1) * 255.0
    # Lighten the terrain FILL: keep only `lighten` of each pixel's darkness
    # (lower = lighter interior). 255 stays 255; mid-gray moves toward white.
    a = 255.0 - (255.0 - a) * lighten
    # THEN punch the dark outline back on top, so edges stay dark on a light map.
    a = np.clip(a - edge * mag, 0, 255)
    im = Image.fromarray(a.astype(np.uint8))
    d = np.asarray(im.convert("1"), dtype=np.uint8)   # Floyd-Steinberg, 0=black
    ink = d == 0                                       # True = black ink
    return ink


def pack_1bpp(ink):
    """Adafruit drawBitmap layout: rows byte-padded, MSB first, 1 = draw."""
    h, w = ink.shape
    rb = (w + 7) // 8
    out = bytearray(rb * h)
    for y in range(h):
        row = ink[y]
        for x in range(w):
            if row[x]:
                out[y * rb + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def carr(name, data):
    lines = [f"static const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 12):
        lines.append("  " + "".join(f"0x{b:02X}," for b in data[i:i + 12]))
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=os.path.join(ROOT, "Map", "SanFranGrey.png"))
    ap.add_argument("--lighten", type=float, default=0.4,
                    help="0..1 terrain-fill darkness kept (lower = lighter inside)")
    ap.add_argument("--contrast", type=float, default=1.9,
                    help="tone contrast boost so the coast/bay read (>1)")
    ap.add_argument("--edge", type=float, default=1.1,
                    help="outline emphasis: darken coastline/edges (0 = off)")
    ap.add_argument("--no-preview", action="store_true")
    args = ap.parse_args()

    ink = process(args.src, args.lighten, args.contrast, args.edge)
    data = pack_1bpp(ink)

    out = ["// AUTO-GENERATED by tools/build_map.py -- do not edit.",
           "// 1bpp dithered area map (SanFranGrey.png) for the MAP screen.",
           "#pragma once", "#include <stdint.h>", "#include <pgmspace.h>", "",
           f"static const uint16_t MAP_BG_W = {W};",
           f"static const uint16_t MAP_BG_H = {H};", "",
           carr("MAP_BG", data), ""]
    with open(OUT_H, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT_H}  ({len(data)/1024:.1f} KB, {W}x{H})")

    if not args.no_preview:
        Image.fromarray((~ink * 255).astype(np.uint8)).save(PREVIEW)
        print(f"preview -> {PREVIEW}")


if __name__ == "__main__":
    main()
