#!/usr/bin/env python3
"""
Turn the top-down aircraft silhouette (plane-marker.png) into an e-paper-ready
1bpp mask the firmware rotates to the plane's heading and blits as the MAP-screen
marker (replacing the old filled-triangle arrow).

Two masks are emitted on a fixed SQUARE canvas (so runtime rotation never clips
and the center is constant regardless of angle):
  MARKER_BODY -- the silhouette itself (drawn BLACK)
  MARKER_HALO -- the silhouette dilated by a few px (drawn WHITE underneath the
                 body) so the plane reads over the busy map.
The source art has the nose pointing UP = heading 0 (north), matching the
firmware's north-up convention.

Output:
  firmware/src/generated/gen_marker.h

Run from the repo root:
    python3 tools/build_marker.py
    python3 tools/build_marker.py --size 44 --halo 2
"""
import argparse, math, os
import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "markers", "plane-marker.png")
OUT_H = os.path.join(ROOT, "firmware", "src", "generated", "gen_marker.h")
PREVIEW = os.path.join(ROOT, "firmware", "src", "generated", "gen_marker_preview.png")


def load_mask(path):
    """Load the silhouette as a boolean ink mask (True = plane)."""
    im = Image.open(path)
    if im.mode == "RGBA":
        a = np.asarray(im.split()[-1], dtype=np.uint8)   # alpha channel
        ink = a > 128
    else:
        g = np.asarray(im.convert("L"), dtype=np.uint8)
        ink = g < 128                                    # dark pixels = plane
    # Tight-crop to the silhouette so scaling is to the plane, not the padding.
    ys, xs = np.where(ink)
    return ink[ys.min():ys.max() + 1, xs.min():xs.max() + 1]


def scale_to(ink, max_dim):
    """Scale the cropped mask so its larger side == max_dim, preserving aspect."""
    h, w = ink.shape
    s = max_dim / max(h, w)
    nw, nh = max(1, round(w * s)), max(1, round(h * s))
    im = Image.fromarray((ink * 255).astype(np.uint8)).resize((nw, nh), Image.LANCZOS)
    return np.asarray(im, dtype=np.uint8) > 128


def place_center(mask, canvas):
    """Center the mask on a square canvas x canvas boolean field."""
    out = np.zeros((canvas, canvas), dtype=bool)
    h, w = mask.shape
    y0, x0 = (canvas - h) // 2, (canvas - w) // 2
    out[y0:y0 + h, x0:x0 + w] = mask
    return out


def pack_1bpp(ink):
    """Adafruit drawBitmap layout: rows byte-padded, MSB first, 1 = draw."""
    h, w = ink.shape
    rb = (w + 7) // 8
    out = bytearray(rb * h)
    for y in range(h):
        row = ink[y]
        for x in range(w):
            if row[x]:
                out[y * rb + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def carr(name, data):
    lines = [f"static const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 12):
        lines.append("  " + "".join(f"0x{b:02X}," for b in data[i:i + 12]))
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--size", type=int, default=44,
                    help="marker's larger dimension in px (before rotation)")
    ap.add_argument("--halo", type=int, default=2,
                    help="white halo thickness in px around the silhouette")
    ap.add_argument("--no-preview", action="store_true")
    args = ap.parse_args()

    ink = scale_to(load_mask(args.src), args.size)
    # Square canvas big enough that any rotation (up to the diagonal) plus the
    # halo fits without clipping. Even size keeps the center on a pixel pair.
    diag = math.ceil(math.hypot(*ink.shape))
    canvas = diag + 2 * args.halo + 2
    canvas += canvas & 1

    body = place_center(ink, canvas)
    halo = ndimage.binary_dilation(body, iterations=args.halo) if args.halo else body

    out = ["// AUTO-GENERATED by tools/build_marker.py -- do not edit.",
           "// 1bpp aircraft marker (plane-marker.png) for the MAP screen,",
           "// rotated to heading at runtime. Nose up = heading 0 (north).",
           "#pragma once", "#include <stdint.h>", "#include <pgmspace.h>", "",
           f"static const int16_t MARKER_W = {canvas};",
           f"static const int16_t MARKER_H = {canvas};", "",
           carr("MARKER_BODY", pack_1bpp(body)), "",
           carr("MARKER_HALO", pack_1bpp(halo)), ""]
    with open(OUT_H, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT_H}  ({canvas}x{canvas}, "
          f"{2 * len(pack_1bpp(body))} bytes)")

    if not args.no_preview:
        prev = np.where(body, 0, np.where(halo, 200, 255)).astype(np.uint8)
        Image.fromarray(prev).save(PREVIEW)
        print(f"preview -> {PREVIEW}")


if __name__ == "__main__":
    main()
